### ISSUE TITLE
哥们哥们 这个问题解决了吗

### ISSUE THREAD

**Issue by wjm0913** [LovesLolita/jiangs-blog-mini-taro#1]
TypeError: Function(...) is not a function

**Comment by LovesLolita** [comment]
> 

没有啊  我估计是dva.js问题

**Comment by LovesLolita** [comment]
我这边 换zustand 了

**Comment by wjm0913** [comment]
https://docs.pmnd.rs/zustand/getting-started/introduction. 这个吗

**Comment by LovesLolita** [comment]
> https://docs.pmnd.rs/zustand/getting-started/introduction. 这个吗

嗯
