### ISSUE TITLE
登录成功后头像不居中的问题

### ISSUE THREAD

**Issue by Ananius** [LovesLolita/jiangs-blog-mini-taro#7]

**Comment by LovesLolita** [comment]
贴一下图

**Comment by Ananius** [comment]
Some time ago, the picture could not be uploaded due to network reasons.
<img width="378" alt="image" src="https://github.com/LovesLolita/jiangs-blog-mini-taro/assets/80749242/16b1e2b2-38a2-4bba-8980-5bd68da91dd9">

**Comment by LovesLolita** [comment]
#7 已解决

**Comment by LovesLolita** [comment]
https://github.com/LovesLolita/jiangs-blog-mini-taro/issues/7 已解决
